<?php

declare(strict_types=1);
/**
 * +----------------------------------------------------------------------
 * | ThinkAdmin Plugin for ThinkAdmin
 * +----------------------------------------------------------------------
 * | 版权所有 2014~2026 ThinkAdmin [ thinkadmin.top ]
 * +----------------------------------------------------------------------
 * | 官方网站: https://thinkadmin.top
 * +----------------------------------------------------------------------
 * | 开源协议 ( https://mit-license.org )
 * | 免责声明 ( https://thinkadmin.top/disclaimer )
 * | 会员特权 ( https://thinkadmin.top/vip-introduce )
 * +----------------------------------------------------------------------
 * | gitee 代码仓库：https://gitee.com/zoujingli/ThinkAdmin
 * | github 代码仓库：https://github.com/zoujingli/ThinkAdmin
 * +----------------------------------------------------------------------
 */

namespace app\admin\controller;

use app\admin\service\WechatService;
use app\service\model\ServiceTemplate;
use app\service\service\AuthService;
use think\admin\Builder;
use think\admin\Controller;
use think\admin\Exception;
use think\admin\extend\CodeExtend;
use think\admin\service\AdminService;
use think\admin\Storage;
use think\admin\storage\LocalStorage;
use think\facade\Cache;
use WeChat\Exceptions\InvalidResponseException;
use WeChat\Exceptions\LocalCacheException;

/**
 * 微信授权绑定
 * @site site
 */
class WechatAuth extends Controller
{
    public $http = '';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->http = "https://{$this->request->host()}";
//        $this->http = "https://dev.zsh88.cn";
    }

    /**
     * 微信授权配置.
     * @auth true
     * @menu true
     * @throws \think\admin\Exception
     */
    public function options()
    {
        $this->vo = AdminService::getSite('wechatcfg',[]);
        $this->thrNotify = sysuri('wechat/api.push/index', [], false, true);
        $service_authurl = url('service/api.push/auth',[],false,true) . '?source=SOURCE';
        if ($this->request->isGet()) {
            try {
                // 生成微信授权链接
                $source = enbase64url(sysuri('admin/index/index', [], false, true) . '#' . $this->request->url());
                $this->authurl = str_replace('source=SOURCE', "source={$source}",  $service_authurl);

                // 授权成功后的参数保存
                if (input('?appid') && input('?appkey')) {
                    $this->vo['type'] = 'thr';
                    $this->vo['thr_appid'] =  input('appid');
                    $this->vo['thr_appkey'] =  input('appkey');
                    AdminService::setSite('wechatcfg',$this->vo);
                    WechatService::ThinkServiceConfig()->setApiNotifyUri($this->thrNotify);
                }
                // 读取授权的微信参数
                $this->wechat = WechatService::ThinkServiceConfig()->getConfig();
            } catch (\Exception $exception) {
                $this->wechat = [];
                $this->message = $exception->getMessage();
            }

            $this->geoip = $this->app->cache->get('mygeoip', '');
            if (empty($this->geoip)) {
                $this->geoip = gethostbyname($this->request->host());
                $this->app->cache->set('mygeoip', $this->geoip, 360);
            }
            $this->title = '微信授权配置';
            $this->fetch();
        } else {
            $config = array_merge((array)$this->vo, $this->request->post('config',[]));
            if ($config['type'] === 'thr') {
                try {
                    WechatService::ThinkServiceConfig()->setApiNotifyUri($this->thrNotify);
                } catch (\Exception $exception) {
                    $this->error($exception->getMessage());
                }
            }
            sysoplog('微信授权配置', '修改微信授权配置成功');
            $this->success('微信授权修改成功！', admuri('', ['uniqid' => uniqid()]));
        }
    }


    /**
     * 上传代码到体验版本
     * @return void
     */
    public function submit_code(): void
    {
        $map = $this->_vali([
            'templateId.require'   => '请选择上传的模版',
        ]);

        $appid = AdminService::getSite('wechatcfg.thr_appid','');
        if (empty($appid)) $this->error('公众号错误');

        $temp = ServiceTemplate::mk()->where(['id' => $map['templateId']])->findOrEmpty();
        if ($temp->isEmpty()) $this->error('模版信息不存在');

        $extJson = json_encode([
            'extEnable' => true,
            'extAppid' => 'wxa81609e357681a00',
            'directCommit' => false,
            'ext' => [
                'API_BASE' => $this->request->domain() . '/',
                'SITE_ID' => (string)$this->site_id
            ]
        ],JSON_UNESCAPED_UNICODE);

        try {
            $result = AuthService::WeMiniCode($appid)->commit($temp->getAttr('template_id') , $extJson, $temp->getAttr('user_version'), $temp->getAttr('user_desc'));
            if (empty($result['errcode']) && $result['errmsg'] === 'ok') {
                $this->success('操作成功');
            } else {
                throw new Exception('上传模版失败，请稍候再试！');
            }
        } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
            $this->error($exception->getMessage());
        }
    }

    /**
     * 审核-提交
     * @return void
     */
    public function audit_submit(): void
    {
        $appid = AdminService::getSite('wechatcfg.thr_appid','');
        $miniCode  = AuthService::WeMiniCode($appid);
        if ($this->request->isPost()){
            $page = $this->request->post('page');
            $data = $this->request->post('data');
            $cate = json_decode(CodeExtend::deSafe64($this->request->post('cate')),true);
            if (empty($cate)) $this->error('请选择类目');

            $data['item_list'][] = [
                "address"       => $page,
                "tag"           => "",
                "first_class"   => $cate['first_class'],
                "second_class"  => $cate['second_class'],
                "first_id"      => (int)$cate['first_id'],
                "second_id"     => (int)$cate['second_id'],
                "title"         => "首页"
            ];

            $preview_info = Cache::get('preview_info');
            if (empty($preview_info)){
                [$medias,$videoList ,$picList] = [sysdata('service.arraign'),[],[]];
                foreach ($medias as $media)  try {
                    $filename = LocalStorage::instance()->path($media['filepath'],true);
                    if (!LocalStorage::instance()->has($media['filepath'],true)){
                        throw new Exception("审核文件{$media['filepath']}不存在");
                    }
                    $result = $miniCode->uploadmedia($filename);
                    if (empty($result['errcode']) && $result['errmsg'] === 'ok') {
                        if ( $result['type'] == 'image'){
                            $picList[] = $result['mediaid'];
                        }else if( $result['type'] == 'video' ){
                            $videoList[] = $result['mediaid'];
                        }
                    }else{
                        throw new Exception('提交审核失败，请稍候再试！');
                    }
                } catch (Exception $exception) {
                    $this->error($exception->getMessage().'；code:'. $exception->getCode());
                }
                $preview_info = [
                    'video_id_list' => $videoList,
                    'pic_id_list' => $picList
                ];
                Cache::set('preview_info',$preview_info,86000*3);
            }

            $data['preview_info'] = $preview_info;

            try {
                $wechatcfg = AdminService::getSite('wechatcfg',[]);
                $result = $miniCode->submitAudit($data);
                if (empty($result['errcode']) && $result['errmsg'] === 'ok') {
                    $wechatcfg['auditid'] = $result['auditid'];
                    AdminService::setSite('wechatcfg',$wechatcfg);
                    $this->success('审核提交成功');
                }else{
                    throw new Exception('提交审核失败，请稍候再试！');
                }
            } catch (Exception $exception) {
                $this->error($exception->getMessage().'；code:'. $exception->getCode());
            }
        }else{
            // 获取小程序页面
            try {
                // 获取小程序类目
                $page = $miniCode->getPage();
                if (empty($page['errcode']) && $page['errmsg'] === 'ok') {
                    $this->page_list = $page['page_list']??[];
                } else {
                    throw new Exception('代码页面列表获取失败，请稍候再试！');
                }
                // 获取小程序类目
                $cate = $miniCode->getCategory();
                if (empty($cate['errcode']) && $cate['errmsg'] === 'ok') {
                    $this->cate_list = $cate['category_list']??[];
                    foreach ($this->cate_list as &$vo){
                        $vo['value'] = CodeExtend::enSafe64(json_encode($vo,JSON_UNESCAPED_UNICODE));
                    }
                } else {
                    throw new Exception('类目名称信息获取失败，请稍候再试！');
                }
            } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
                $this->error($exception->getMessage());
            }
//
            $this->vo['order_path'] = 'familyGroup/family/list';  //小程序订单中心path
            $this->vo['page'] = $this->page_list[0]??'';  //小程序订单中心path
            $this->fetch();

        }

    }

    /**
     * 审核-撤销
     * @return void
     */
    public function audit_revoke(): void
    {
        try {
            $miniCode  = AuthService::WeMiniCode(AdminService::getSite('wechatcfg.thr_appid',''));
            $result = $miniCode->undoCodeAudit();
            if (empty($result['errcode']) && $result['errmsg'] === 'ok') {
                $this->success('审核撤销成功');
            }else{
                throw new Exception('撤销审核失败，请稍候再试！');
            }

        } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
            $this->error($exception->getMessage());
        }
    }

    /**
     * 发布小程序
     * @return void
     */
    public function publish(): void
    {
        try {
            $miniCode  = AuthService::WeMiniCode(AdminService::getSite('wechatcfg.thr_appid',''));
            $result = $miniCode->publishRelease();
            if (empty($result['errcode']) && $result['errmsg'] === 'ok') {
                $this->success('小程序发布成功');
            }else{
                throw new Exception('发布小程序失败，请稍候再试！');
            }
        } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
            $this->error($exception->getMessage());
        }
    }


    /**
     * 小程序检测数据
     * @return void
     * @throws InvalidResponseException
     * @throws LocalCacheException
     */
    public function serverConfig(): void
    {
        if ($this->request->isGet()){
            $this->check = [
                'server' =>['name' => '服务器域名','data' => [],'msg' => '检查通过','status' => 1],
                'webview' =>['name' => '业务域名','data' => [],'msg' => '检查通过','status' =>1],
            ];
            $domain = AuthService::WeMiniDomain(AdminService::getSite('wechatcfg.thr_appid',''));
            foreach ($domain->modifyDomain('get') as $key => $val) if (in_array($key,['requestdomain','uploaddomain','downloaddomain'])) {
                $name = ['requestdomain' => 'request','uploaddomain' => 'uploadFile','downloaddomain' => 'downloadFile'][$key];
                $this->check['server']['data'][$key] =  ['name' => $name,'list' => $val];

                if ($this->check['server']['status'] == 1 && !in_array($this->http,$val) ){
                    $this->check['server']['status'] = 0;
                    $this->check['server']['msg'] = "{$name} 域名检测未通过";
                }
            }
            foreach ($domain->setWebViewDomain('get') as $key => $val) if (in_array($key,['webviewdomain'])) {
                $name = ['webviewdomain' => 'webview'][$key];
                $this->check['webview']['data'][$key] = ['name' => $name,'list' => $val];
                if ($this->check['webview']['status'] == 1 && !in_array($this->http,$val) ){
                    // pr($http, $this->check['webview'] , in_array($http,$val));
                    $this->check['webview']['status'] = 0;
                    $this->check['webview']['msg'] = "{$name} 域名检测未通过";
                }
            }


            $this->fetch();
        }else{
            $action = $this->request->get('action');
            switch ($action){
                case 'domain':  // 服务器域名同步覆盖
                    $domain = AuthService::WeMiniDomain(AdminService::getSite('wechatcfg.thr_appid',''));
                    $type = $this->request->get('type');
                    try {
                        if ($type == 'server'){
                            $domain->modifyDomain('set',[
                                'requestdomain' => [$this->http],
                                'uploaddomain' => [$this->http],
                                'downloaddomain' => [$this->http],
                            ]);
                        }
                        if ($type == 'webview'){
                            $domain->setWebViewDomain('set',[
                                'webviewdomain' => [$this->http],
                            ]);
                        }
                        $this->success('操作成功');
                    } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
                        $this->error($exception->getMessage());
                    }
                    break;
            }
        }

    }


    /**
     * 异步获取版本信息
     * @return void
     * @throws InvalidResponseException
     * @throws LocalCacheException
     */
    public function getTrialVersion(): void
    {

        $this->wechat = WechatService::ThinkServiceConfig()->getConfig();
        $miniCode  = AuthService::WeMiniCode($this->wechat['authorizer_appid']);

        $this->templates = ServiceTemplate::mk()->where(['type' => 'temp'])->order('create_time desc')->select()->toJson();

        // 获取体验二维码
        $this->qrcode  = 'data:image/png;base64,'. base64_encode($miniCode->getQrcode()) ;

        try {
            // 获取版本信息
            $version = $miniCode->getVersioninfo();
            if (empty($version['errcode']) && $version['errmsg'] === 'ok') {
                $this->version = $version;
            } else {
                throw new Exception('审核状态获取失败，请稍候再试！');
            }
        } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
            $this->error($exception->getMessage());
        }

        try {
            // 获取审核状态
            $audit = $miniCode->getLatestAuditatus();
            if (empty($audit['errcode']) && $audit['errmsg'] === 'ok') {
                if (isset($audit['screenshot']) && !empty($audit['screenshot'])){
                    $audit['screenshot'] = str2arr($audit['screenshot'],'|');
                }
                $this->audit = $audit;
            } else {
                throw new Exception('审核状态获取失败，请稍候再试！');
            }

        } catch (LocalCacheException|InvalidResponseException|Exception $exception) {
        }
        $this->fetch();
    }

    /**
     * 绑定小程序.
     * @auth true
     * @throws \think\admin\Exception
     */
    public function options_wxapp()
    {
        if ($this->request->isGet()) {
            $data = sysdata('plugin.wechat.wxapp') ?: [];
            Builder::mk()
                ->addTextInput('appid', '小程序', 'AppId', true, '<b>必选</b>，微信小程序 AppID 需要微信公众号平台获取！', '^wx[0-9a-z]{16}$', ['maxlength' => 18])
                ->addTextInput('appkey', '小程序密钥', 'AppSecret', true, '<b>必选</b>，微信小程序 AppSecret 需要微信公众号平台获取！', '^[0-9a-z]{32}$', ['maxlength' => 32])
                ->addSubmitButton('保存参数')->addCancelButton()
                ->fetch(['vo' => ['appid' => $data['appid'] ?? '', 'appkey' => $data['appkey'] ?? '']]);
        } else {
            sysdata('plugin.wechat.wxapp', $this->_vali([
                'appid.require' => '小程序ID不能为空！',
                'appkey.require' => '小程序密钥不能为空！',
            ]));
            $this->success('参数保存成功！');
        }
    }


}
